language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r hohyunjun-springboot2-webservice *
  - mkdir -p deploy
  - mv hohyunjun-springboot2-webservice.zip deploy/hohyunjun-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hohyunjun-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hohyunjun-springboot-build
    key: hohyunjun-springboot2-webservice.zip
    bundle_type: zip
    application: hohyunjun-springboot2-webservice # AWS 웹 콘솔에서 등록한 Codedeploy 어플리케이션
    deployment_group: hohyunjun-springboot2-webservice-group # 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wjsghgus1221@gmail.com